### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by svm-zhang** [arq5x/piledriver#6]
Hi Aaron,

Thanks for the program! I tried to install piledriver on a local server that I have been using. I get the following error when trying to make:

In file included from /N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:10:
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:38: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:39: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:40: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:41: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:42: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:43: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:45: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:46: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:47: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:48: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:49: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:50: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:52: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:53: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:54: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:55: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:58: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:59: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:60: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.h:61: error: 'uint64_t' does not name a type
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp: In member function 'void BamTools::PileDriverPileupFormatVisitor::Header()':
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:444: warning: comparison between signed and unsigned integer expressions
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp: In member function 'virtual void BamTools::PileDriverPileupFormatVisitor::Visit(const BamTools::PileupPosition&)':
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:526: error: 'struct BamTools::SampleCoverage' has no member named 'ins_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:528: error: 'struct BamTools::SampleCoverage' has no member named 'ins_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:532: error: 'struct BamTools::SampleCoverage' has no member named 'ins_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:534: error: 'struct BamTools::SampleCoverage' has no member named 'ins_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:543: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:544: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:545: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:546: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:550: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:551: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:552: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:553: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:560: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:561: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:562: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:563: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:567: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:568: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:569: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:570: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:578: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:579: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:580: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:581: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:585: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:586: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:587: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:588: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:596: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:597: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:598: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:599: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:603: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:604: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:605: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:606: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:614: error: 'struct BamTools::SampleCoverage' has no member named 'del_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:615: error: 'struct BamTools::SampleCoverage' has no member named 'del_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:619: error: 'struct BamTools::SampleCoverage' has no member named 'del_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:620: error: 'struct BamTools::SampleCoverage' has no member named 'del_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:683: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:683: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:684: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:684: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:685: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:685: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:686: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:686: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:687: error: 'struct BamTools::SampleCoverage' has no member named 'del_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:687: error: 'struct BamTools::SampleCoverage' has no member named 'del_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:688: error: 'struct BamTools::SampleCoverage' has no member named 'ins_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:688: error: 'struct BamTools::SampleCoverage' has no member named 'ins_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:691: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:691: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:692: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:692: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:693: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:693: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:694: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:694: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:698: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:699: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:700: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:701: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:702: error: 'struct BamTools::SampleCoverage' has no member named 'del_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:703: error: 'struct BamTools::SampleCoverage' has no member named 'ins_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:706: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:707: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:708: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:709: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:713: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:714: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:715: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:716: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:717: error: 'struct BamTools::SampleCoverage' has no member named 'del_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:718: error: 'struct BamTools::SampleCoverage' has no member named 'ins_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:721: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:722: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:723: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:724: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:728: warning: comparison between signed and unsigned integer expressions
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:761: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:761: error: 'struct BamTools::SampleCoverage' has no member named 'a_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:762: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:762: error: 'struct BamTools::SampleCoverage' has no member named 'a_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:765: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:765: error: 'struct BamTools::SampleCoverage' has no member named 'c_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:766: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:766: error: 'struct BamTools::SampleCoverage' has no member named 'c_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:769: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:769: error: 'struct BamTools::SampleCoverage' has no member named 'g_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:770: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:770: error: 'struct BamTools::SampleCoverage' has no member named 'g_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:773: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:773: error: 'struct BamTools::SampleCoverage' has no member named 't_fwd_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:774: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:774: error: 'struct BamTools::SampleCoverage' has no member named 't_rev_totqual'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:777: error: 'struct BamTools::SampleCoverage' has no member named 'del_fwd_cnt'
/N/dc2/projects/simozhan/software/ngs/util/piledriver-master/src/toolkit/piledriver.cpp:777: error: 'struct BamTools::SampleCoverage' has no member named 'del_rev_cnt'
make[2]: **\* [src/toolkit/CMakeFiles/bamtools_cmd.dir/piledriver.cpp.o] Error 1
make[1]: **\* [src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make: **\* [all] Error 2

Sorry for this long list of errors...

And here is the server system info:
Linux h1 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Dec 13 06:58:20 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

And I already got bamtools 2.3.0 installed and worked perfectly on the server.

Could you please help me on this? Thanks!

Simo

**Comment by svm-zhang** [comment]
Hi Aaron,

I added #include <stdint.h> at the beginning of piledriver.h, and it fixed all the errors. I can use it now.

I am gonna go ahead close this ticket.

Thanks,
Simo

**Comment by arq5x** [comment]
Could you provide a Pull Request with the fix or provide the include you used?
